# Site
title:              Victoria Blessing
bio:                'Operations Engineer @ Texas A&M University - College of Architecture'
description:        "A site about me, Victoria Blessing."
reading_time:       false
words_per_minute:   200
logo:               'assets/img/headshot.png'
background:         'assets/img/sunflowers.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                http://victoriablessing.com
url:                http://vblessing.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   vblessing

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              victoriaannblessing@gmail.com
twitter:            _vblessing
facebook:           victoriaannblessing
github:             vblessing
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           victoriablessing
#xing:              username
instagram:          rocketgirl1200
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
